version: 1
services:
  - type: web
    name: Frontend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    rootDir: front   

  - type: web
    name: Backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod  
    autoDeploy: true
    rootDir: back    
