name: deployTEST

on:
  push:
    branches:
      - main  
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: Login Docker
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - 
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      
      - name: Build and push backend image
        run: |
          docker buildx build --push \
            --file ./back/Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}nest-backend:latest 
            ./back

      - name: Build and push frontend image
        run: |
          docker buildx build --push \
            --file ./front/Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}next-frontend:latest 
            ./front


      - name: Deploy using docker-compose
        run: |
          docker-compose up -d
